name: Frontend Build
run-name: Frontend deployment update triggered by ${{ github.actor }}.
on:
  push:
    branches:
      - deployment
    paths:
      - "frontend/**"
      - ".github/workflows/frontendBuild.yml"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  packages: write

jobs:
  frontend-build-test:
    name: Build and test the Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache Node Modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ${{ github.workspace }}/frontend/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

    - name: Install Dependecies
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm install

    - name: Retrieve the env vars
      run: echo "${{ secrets.FE_ENV }}" > .env

    - name: Test and coverage
      continue-on-error: true
      run: npm test

    - name: Build application
      run: npm run build

  docker:
    name: Docker Job
    permissions:
      packages: write
    runs-on: ubuntu-latest
    needs:
      - frontend-build-test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: frontend
        push: true
        tags: ghcr.io/${{ github.repository_owner}}/bootcamp26-frontend:latest

  deploy:
    name: EC2 Deploy
    permissions:
      packages: write
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to AWS instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_INSTANCE_IP }}
        username: ${{ secrets.AWS_INSTANCE_USERNAME }}
        key: ${{ secrets.AWS_INSTANCE_PRIVATE_KEY }}
        script: |
          sudo docker pull ghcr.io/${{ github.repository_owner}}/bootcamp26-frontend:latest
          sudo docker stop bootcamp26-frontend || true
          sudo docker rm bootcamp26-frontend || true
          sudo docker run -d --name bootcamp26-frontend -p 80:80 ghcr.io/${{ github.repository_owner}}/bootcamp26-frontend:latest

          

    