name: Frontend Build
run-name: Frontend deployment update triggered by ${{ github.actor }}.
on:
  push:
    branches:
      - deployment
    paths:
      - "frontend/**"
      - ".github/workflows/frontendBuild.yml"
  pull_request:
    types: [opened, synchronize, reopened]

env:
  AWS_HOST: ${{ secrets.AWS_INSTANCE_IP }}
  AWS_USERNAME: ${{ secrets.AWS_INSTANCE_USERNAME }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_INSTANCE_PRIVATE_KEY }}

permissions:
  packages: write

jobs:
  frontend-build:
    name: Build and test the Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 8
    defaults:
      run:
        working-directory: frontend
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache Node Modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

    - name: Install Dependecies
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm install

    - name: Retrieve the env vars
      run: echo "${{ secrets.FE_ENV }}" > .env

    - name: Test and coverage
      continue-on-error: true
      run: npm test

    - name: Build application
      run: npm run build

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: frontend
        push: true
        tags: ghcr.io/${{ github.repository_owner}}/bootcamp26-frontend:${{ github.sha }}

  deploy:
    name: EC2 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 8
    needs:
      - frontend-build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to AWS instance
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_USERNAME }}@${{ env.AWS_HOST }}'
          docker pull ghcr.io/${{ github.repository_owner}}/bootcamp26-frontend:${{ github.sha }} &&
          docker stop bootcamp26-frontend || true &&
          docker rm bootcamp26-frontend || true &&
          docker run -d --name bootcamp26-frontend -p 80:80 ghcr.io/${{ github.repository_owner}}/bootcamp26-frontend:${{ github.sha }}
        '

    # - name: Deploy to AWS instance
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.AWS_INSTANCE_IP }}
    #     username: ${{ secrets.AWS_INSTANCE_USERNAME }}
    #     key: ${{ secrets.AWS_INSTANCE_PRIVATE_KEY }}
    #     script: |
    #       sudo docker pull ghcr.io/${{ github.repository_owner}}/bootcamp26-frontend:${{ github.sha }}
    #       sudo docker stop bootcamp26-frontend || true
    #       sudo docker rm bootcamp26-frontend || true
    #       sudo docker run -d --name bootcamp26-frontend -p 80:80 ghcr.io/${{ github.repository_owner}}/bootcamp26-frontend:${{ github.sha }}

          

    